### PR TITLE
Solved #163 added  : partition list leet code

### PR DESCRIPTION
**Pull request by sameersrivastava13**
@i-vishi Please review the code and I have also added a readme file with the code which includes the actual problem statement.

### CODE REVIEW

**Comment by sameersrivastava13** [comment]
@i-vishi can you please review the code.

**Comment by sameersrivastava13** [comment]
@i-vishi can you please review and add the label please.

**Review by i-vishi — CHANGES_REQUESTED** [review]
Do not make a directory named Leetcode. Make the directory by algorithm name which in this case can be LinkedListPartition.
Follow the directory structure as 
`algorithm-name/programming-language/code.extension`

@sameersrivastava13 make the necessary changes

**Comment by sameersrivastava13** [comment]
> Do not make a directory named Leetcode. Make the directory by algorithm name which in this case can be LinkedListPartition.
> Follow the directory structure as
> `algorithm-name/programming-language/code.extension`
> 
> @sameersrivastava13 make the necessary changes

Done.

**Pull request merged**
