### PR TITLE
Added Kadane's algorithm By zahinekbal

### PR DESCRIPTION
**Pull request by zahinekbal**
I added Kadane's algorithm for maximum- subarray-sum  in Array Folder with Explanation ,Algorithms ,Example & Implementation.
i.e:- 
Arrays/Maximum_Subarray_Sum/KADANE'S_ALGORITHM/C++/Kadane's_algorithm.c++
kindly check my code & review my PR.....

### CODE REVIEW

**Review by i-vishi — COMMENTED** [review]
Comment all the explanation and examples. Your file should only contain the algorithm and comments for explanation and relevant examples. Currently, the code can not be compiled as some lines needs to be commented

**Comment by zahinekbal** [comment]
Ohk sure I m checking I will update pr soon

**Comment by zahinekbal** [comment]
@i-vishi no need to remove the explanation right only I have to comment it

**Comment by i-vishi** [comment]
I saw your PR. You have added two main functions in one file. If they are different algorithms then make separate files. And yes, no need to remove the explanation just keep it in comments.

**Comment by zahinekbal** [comment]
Ohk sure I will update my code nd will create PR soon ..

**Comment by i-vishi** [comment]
I am closing this PR as you have given another PR.
Please delete your PR if you are going to give another PR for the same algorithm or try to commit changes in the same PR

**Pull request closed without merging**
