### PR TITLE
Move python GCD code from euclidean distance to GCD.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
Fixes: #785

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
HI @ravivarshney01, can you tell me why it was closed rather than merging?

**Comment by ravivarshney01** [comment]
@i-vishi is already working on this and you have moved only one file

**Comment by Anupam-dagar** [comment]
I just did what the issue said. I think its better to close down the issue and not even fund it for the same.
Thanks for the clarification though.

**Comment by ravivarshney01** [comment]
and if you are looking for issue hunt then create an issue and i will request that issue for reward.😅

**Pull request closed without merging**
