### PR TITLE
Added the CPP code for finding no of ways to traverse a grid

### PR DESCRIPTION
**Pull request by raj5036**
Please review the changes(Issue #163 )

### CODE REVIEW

**Review by i-vishi — COMMENTED** [review]
remove the binary file

**Review by i-vishi — COMMENTED** [review]
Also remove input and output files. Only keep the algorithm. You can add example input and output in the comments of the code

**Review by i-vishi — COMMENTED** [review]
remove binary file and input / output files. Only keep the algorithm

**Comment by raj5036** [comment]
@i-vishi Okay.

**Comment by raj5036** [comment]
Is it okay now?

**Review by i-vishi — APPROVED** [review]

**Pull request merged**
